# Generated by Django 5.0.2 on 2024-03-08 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
                ('subject', models.CharField(max_length=30)),
            ],
        ),
    ]
