# Generated by Django 5.0.2 on 2024-02-29 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_trainerprofile_studentprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainerprofile',
            name='trainer',
        ),
        migrations.DeleteModel(
            name='StudentProfile',
        ),
        migrations.DeleteModel(
            name='TrainerProfile',
        ),
    ]
