# Generated by Django 5.0.2 on 2024-02-29 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_trainerprofile_trainer_delete_studentprofile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='bio',
        ),
    ]
