# Generated by Django 5.0.2 on 2024-02-29 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_students', '0003_remove_studentprofile_assigned_trainers_and_more'),
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerprofile',
            name='assigned_students',
            field=models.ManyToManyField(blank=True, to='gym_students.studentprofile'),
        ),
    ]
