# Generated by Django 5.0.2 on 2024-02-29 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0002_trainerprofile_assigned_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerprofile',
            name='trainer_bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainerprofile',
            name='trainer_profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/profile_pictures/'),
        ),
    ]
