# Generated by Django 4.0 on 2024-03-13 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_students', '0006_alter_studentprofile_assigned_trainer'),
        ('trainer', '0003_trainerprofile_trainer_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainerprofile',
            name='assigned_students',
            field=models.ManyToManyField(blank=True, to='gym_students.StudentProfile'),
        ),
    ]
