# Generated by Django 5.0.2 on 2024-03-13 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0004_alter_trainerprofile_assigned_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainerprofile',
            name='trainer_profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
