# Generated by Django 5.0.2 on 2024-02-29 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_students', '0001_initial'),
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='assigned_trainers',
            field=models.ManyToManyField(blank=True, related_name='assigned_trainers', to='trainer.trainerprofile'),
        ),
    ]
