# Generated by Django 5.0.2 on 2024-02-29 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_students', '0002_studentprofile_assigned_trainers'),
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='assigned_trainers',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='assigned_trainer',
            field=models.ManyToManyField(blank=True, to='trainer.trainerprofile'),
        ),
    ]
