# Generated by Django 5.0.2 on 2024-02-29 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_students', '0003_remove_studentprofile_assigned_trainers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='student_bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='student_profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/profile_pictures/'),
        ),
    ]
