# Generated by Django 5.0.2 on 2024-03-29 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_students', '0009_alter_order_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Student_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym_students.studentprofile'),
        ),
    ]
